### ISSUE TITLE
Dependency deprecation notice

### ISSUE THREAD

**Issue by Renegade334** [phergie/phergie-irc-plugin-react-scaffold#12]
On running `bin/phergie-scaffold`, the following is returned before each prompt:

> PHP Deprecated:  "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead. in /snip/phergie/phergie-irc-plugin-react-scaffold/vendor/symfony/console/Symfony/Component/Console/Helper/HelperSet.php on line 82

**Comment by chrismou** [comment]
Confirmed, I'm getting the same.

I noticed that a composer update has upgraded symfony console & process from 2.4 to 2.7, which will explain the deprecation notice suddenly appearing.

The simplest fix here will be to just switch out the console/process requirements from ~2.4 to 2.4.* in composer.json

**Comment by svpernova09** [comment]
Would be open to a better fix, but this should resolve the warnings until then.
