### ISSUE TITLE
Travis CI links sometimes use wrong URL

### ISSUE THREAD

**Issue by PSchwisow** [phergie/phergie-irc-plugin-react-scaffold#7]
README.md.twig uses the following for linking to Travis CI:

```php
[![Build Status](https://secure.travis-ci.org/{{composer_name}}.png?branch=master)](http://travis-ci.org/{{composer_name}})
```

Travis's URLs are actually based on the repo URL, not the composer name. Often this is the same, but it is not guaranteed to be. (Particularly if the user's GitHub username does not match the vendor prefix.)

See https://github.com/WyriHaximus/PhergieUrl/blob/master/README.md as an example (neither vendor name nor package name match their counterparts in GitHub.)

**Comment by PSchwisow** [comment]
PR to fix this is https://github.com/phergie/phergie-irc-plugin-react-scaffold/pull/9

**Comment by elazar** [comment]
Merged. Thanks!
